DROP DATABASE audiroDB;
CREATE DATABASE audiroDB;

USE audiroDB;

/* User */
DROP TABLE IF EXISTS user;

CREATE TABLE User(
                     USER_ID BIGINT NOT NULL PRIMARY KEY auto_increment,
                     NAME VARCHAR(20) NOT NULL,
                     TOKEN VARCHAR(200),
                     NICKNAME VARCHAR(100) NOT NULL UNIQUE,
                     PROFILE_MESSAGE VARCHAR(100) NULL,
                     PROFILE_IMG VARCHAR(200) NOT NULL DEFAULT 'https://t1.daumcdn.net/cfile/tistory/2513B53E55DB206927',
                     EMAIL VARCHAR(50),
                     ROLE VARCHAR(20),
                     REFRESH_TOKEN VARCHAR(500)
                 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
UPDATE User SET role = "ROLE_ADMIN" WHERE email="fanngineer@gmail.com";
INSERT INTO User (NAME, TOKEN, NICKNAME) VALUES ('sohee', 'abv12efw-- sedfwerg', 'sohee');
INSERT INTO User (NAME, TOKEN, NICKNAME) VALUES ('gaok', 'abv12eqwqdfwerg', 'gaok');
INSERT INTO User (NAME, TOKEN, NICKNAME, PROFILE_MESSAGE, EMAIL) VALUES ('sungwhan', 'webv12ef1231', 'sungwhan','나의 상태 메세지', 'asdklfjkdls@gmail.com');
INSERT INTO User (NAME, TOKEN, NICKNAME) VALUES ('hosung', '12wrtsedddfwerg', 'hosung');


/* Song */
DROP TABLE IF EXISTS Song;

CREATE TABLE Song(
    SONG_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SONG_IMG VARCHAR(200) NOT NULL,
    SONG_TITLE VARCHAR(50) NOT NULL,
    SINGER VARCHAR(50) NOT NULL,
    SONG_URL VARCHAR(200) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO Song (SONG_IMG, SONG_TITLE, SINGER, SONG_URL) VALUES('http://image_path.~~~', 'Ditto', 'New Jeans', 'https://yutube.Ditto~~~');
INSERT INTO Song (SONG_IMG, SONG_TITLE, SINGER, SONG_URL) VALUES('http://image_path.~~~', 'Hype boy', 'New Jeans', 'https://yutube.Hype boy~~~');
INSERT INTO Song (SONG_IMG, SONG_TITLE, SINGER, SONG_URL) VALUES('http://image_path.~~~', '기다린만큼 더', '검정치마', 'https://yutube.black~~~');
INSERT INTO Song (SONG_IMG, SONG_TITLE, SINGER, SONG_URL) VALUES('http://image_path.~~~', 'Hilarious', 'Charlie Puth', 'https://yutube.Hilarious~~~');

/* Spot */
DROP TABLE IF EXISTS Spot;

CREATE TABLE Spot(
    SPOT_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SPOT_NAME VARCHAR(200) NOT NULL,
    SPOT_ADDR VARCHAR(200) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT Spot (SPOT_NAME, SPOT_ADDR) VALUES('역삼점', '서울시 강남구 역삼동~');
INSERT SPOT (SPOT_NAME, SPOT_ADDR) VALUES('신촌점', '서울시 서대문구 신촌동~');
INSERT SPOT (SPOT_NAME, SPOT_ADDR) VALUES('성수점', '서울시 성동구 성수동~');
INSERT SPOT (SPOT_NAME, SPOT_ADDR) VALUES('신사점', '서울시 강남구 신사동~');
/* Gift */
DROP TABLE IF EXISTS Gift;

CREATE TABLE Gift(
    GIFT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    SPOT_ID BIGINT NOT NULL,
    SONG_ID BIGINT NOT NULL,
    GIFT_IMG VARCHAR(200) NOT NULL,
    IS_OPEN BOOLEAN NOT NULL DEFAULT TRUE,
    GIFT_TAG VARCHAR(100) NULL,
    REG_TIME TIMESTAMP NOT NULL DEFAULT NOW(),
    GIFT_FEEDBACK1 INT NOT NULL DEFAULT 0,
    GIFT_FEEDBACK2 INT NOT NULL DEFAULT 0,
    GIFT_FEEDBACK3 INT NOT NULL DEFAULT 0,
    GIFT_FEEDBACK4 INT NOT NULL DEFAULT 0,
    IS_MANITO BOOLEAN NOT NULL DEFAULT TRUE,
    FOREIGN KEY (USER_ID) REFERENCES User(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (SPOT_ID) REFERENCES Spot(SPOT_ID) ON DELETE CASCADE,
    FOREIGN KEY (SONG_ID) REFERENCES Song(SONG_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO Gift (GIFT_IMG, USER_ID, SPOT_ID, SONG_ID) VALUES ('https://www.naver.com/gift1', 2, 1, 1);
INSERT INTO Gift (GIFT_IMG, USER_ID, SPOT_ID, SONG_ID, GIFT_TAG) VALUES ('https://www.naver.com/gift1', 2, 1, 1, "SUNNY");
INSERT INTO Gift (GIFT_IMG, USER_ID, SPOT_ID, SONG_ID) VALUES ('https://cdn.discordapp.com/attachments/1056882470429138968/1068081563310506014/Notes_230126_170914.jpg', 4, 1, 1);
INSERT INTO Gift (GIFT_IMG, USER_ID, SPOT_ID, SONG_ID) VALUES ('https://cdn.discordapp.com/attachments/1056882470429138968/1068081563310506014/Notes_230126_170914.jpg', 3, 2, 2);
INSERT INTO Gift (GIFT_IMG, USER_ID, SPOT_ID, SONG_ID) VALUES ('https://cdn.discordapp.com/attachments/1056882470429138968/1068081563310506014/Notes_230126_170914.jpg', 2, 2, 1);
INSERT INTO Gift (GIFT_IMG, USER_ID, SPOT_ID, SONG_ID) VALUES ('https://cdn.discordapp.com/attachments/1056882470429138968/1068081563310506014/Notes_230126_170914.jpg', 1, 1, 1);

/* Postcard */
DROP TABLE IF EXISTS Postcard;

CREATE TABLE Postcard(
    POSTCARD_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SEND_ID BIGINT NOT NULL,
    SPOT_ID BIGINT NOT NULL,
    SONG_ID BIGINT NOT NULL,
    POSTCARD_IMG VARCHAR(200) NOT NULL,
    REG_TIME TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY (SEND_ID) REFERENCES User(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (SPOT_ID) REFERENCES Spot(SPOT_ID) ON DELETE CASCADE,
    FOREIGN KEY (SONG_ID) REFERENCES Song(SONG_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO Postcard (SEND_ID, SPOT_ID, SONG_ID, POSTCARD_IMG) VALUES (2, 1, 1, 'IMGE PATH ~~~');
INSERT INTO Postcard (SEND_ID, SPOT_ID, SONG_ID, POSTCARD_IMG) VALUES (1, 4, 2, 'IMGE PATH ~~~');
INSERT INTO Postcard (SEND_ID, SPOT_ID, SONG_ID, POSTCARD_IMG) VALUES (3, 2, 4, 'IMGE PATH ~~~');
/* Musicmate */
DROP TABLE IF EXISTS Musicmate;

CREATE TABLE Musicmate(
    MUSICMATE_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    MATE_ID BIGINT NOT NULL,
    IS_MATE BOOLEAN NOT NULL DEFAULT TRUE,
    IS_BLOCK BOOLEAN NOT NULL DEFAULT FALSE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO Musicmate (USER_ID, MATE_ID) VALUES (2, 3);
INSERT INTO Musicmate (USER_ID, MATE_ID) VALUES (2, 1);
INSERT INTO Musicmate (USER_ID, MATE_ID) VALUES (4, 2);
INSERT INTO Musicmate (USER_ID, MATE_ID) VALUES (1, 3);

/* SongMeta */
DROP TABLE IF EXISTS SongMeta;

CREATE TABLE SongMeta(
    SONG_META_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SONG_ID BIGINT NOT NULL,
    SPOT_ID BIGINT NOT NULL,
    SONG_LIKED INT NOT NULL DEFAULT 0,
    GIFT_CNT INT NOT NULL DEFAULT 0,
    UPDATE_TIME TIMESTAMP NOT NULL DEFAULT NOW()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO SongMeta (SONG_ID, SPOT_ID) VALUES(1, 1);
INSERT INTO SongMeta (SONG_ID, SPOT_ID) VALUES(1, 2);
INSERT INTO SongMeta (SONG_ID, SPOT_ID) VALUES(2, 2);
INSERT INTO SongMeta (SONG_ID, SPOT_ID) VALUES(2, 3);
INSERT INTO SongMeta (SONG_ID, SPOT_ID) VALUES(1, 3);
INSERT INTO SongMeta (SONG_ID, SPOT_ID) VALUES(2, 1);
INSERT INTO SongMeta (SONG_ID, SPOT_ID) VALUES(4, 1);

select * from user;
select * from Gift;
select * from song;
select * from spot;
select * from songmeta;