CREATE DATABASE audiroDB;

USE audiroDB;

/* User */
DROP TABLE IF EXISTS USER;

CREATE TABLE USER(
    USER_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL,
    TOKEN VARCHAR(200) NOT NULL,
    NICKNAME VARCHAR(20) NOT NULL UNIQUE,
    PROFILE_MESSAGE VARCHAR(100) NULL,
    PROFILE_IMG VARCHAR(200) NOT NULL DEFAULT 'https://t1.daumcdn.net/cfile/tistory/2513B53E55DB206927'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO USER (NAME, TOKEN, NICKNAME) VALUES ('sohee', 'abv12efwsedfwerg', 'sohee');
INSERT INTO USER (NAME, TOKEN, NICKNAME) VALUES ('gaok', 'abv12eqwqdfwerg', 'gaok');
INSERT INTO USER (NAME, TOKEN, NICKNAME) VALUES ('sungwhan', 'webv12ef1231', 'sungwhan');
INSERT INTO USER (NAME, TOKEN, NICKNAME) VALUES ('hosung', '12wrtsedddfwerg', 'hosung');