import React from 'react';
import { useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link';
import Header from "../components/Header";
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const[likes,setLikes]= React.useState(0)
  
  function handleClick(){
    setLikes(likes+1)
  }

  return (
    <>
      <Header/>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <main className={styles.main}>
        <div className={styles.description}>
          {/* <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p> */}
          <button onClick={handleClick}>Like</button>
          {likes}
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/audiro.png"
            alt="Next.js Logo"
            width={180}
            height={100}
            priority
          />
          
        </div>
          <h1 className="title">
            <Link href="/login/Login">로그인 해주세요
              <div className={styles.thirteen}>
                <Image
                  src="/thirteen.svg"
                  alt="login"
                  width={40}
                  height={31}
                  priority
                /> 로그인하기
              </div>
            </Link>
          </h1>
        


      </main>
    </>
  )
}
